// Generated by CoffeeScript 1.6.3
/*

* はてなブログの記事の日付に六曜を表示する

** 使い方

以下をコピーして デザイン編集 → カスタマイズ → フッタHTML に貼り付け

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://rawgithub.com/hitode909/hatenablog-unofficial-modules/master/rokuyo.js"></script>

旧暦を取得するWeb APIを利用しています．
- http://api.sekido.info/qreki?output=usage

日付が途中で改行して崩れる場合はいかのようなCSSを指定すれば直るかもしれない

.date {
  display: inline-block;
  width: auto;
}
*/


(function() {
  $(function() {
    var handle_article, main;
    handle_article = function($article) {
      var day, load, month, year;
      if ($article.prop('rokuyou-loaded')) {
        return;
      }
      $article.prop('rokuyou-loaded', true);
      year = +$article.find('.date-year').text();
      month = +$article.find('.date-month').text();
      day = +$article.find('.date-day').text();
      load = $.ajax({
        url: 'http://api.sekido.info/qreki',
        dataType: 'jsonp',
        data: {
          year: year,
          month: month,
          day: day,
          output: 'jsonp'
        }
      });
      return load.done(function(res) {
        var $rokuyou, rokuyou;
        rokuyou = res.rokuyou_text;
        $rokuyou = $('<span>');
        $rokuyou.addClass('rokuyou');
        $rokuyou.text(rokuyou);
        return $article.find('.date a').append($rokuyou);
      });
    };
    main = function() {
      return ($('article')).each(function() {
        return handle_article($(this));
      });
    };
    main();
    return setInterval(function() {
      return main();
    }, 1000);
  });

}).call(this);
