// Generated by CoffeeScript 1.6.3
/*
 * はてなブログの日付に六曜を表示する
*/


(function() {
  $(function() {
    var handle_article, main;
    handle_article = function($article) {
      var day, load, month, year;
      if ($article.prop('rokuyou-loaded')) {
        return;
      }
      $article.prop('rokuyou-loaded', true);
      year = +$article.find('.date-year').text();
      month = +$article.find('.date-month').text();
      day = +$article.find('.date-day').text();
      load = $.ajax({
        url: 'http://api.sekido.info/qreki',
        dataType: 'jsonp',
        data: {
          year: year,
          month: month,
          day: day,
          output: 'jsonp'
        }
      });
      return load.done(function(res) {
        var $rokuyou, rokuyou;
        rokuyou = res.rokuyou_text;
        $rokuyou = $('<span>');
        $rokuyou.addClass('rokuyou');
        $rokuyou.text(rokuyou);
        return $article.find('.date a').append($rokuyou);
      });
    };
    main = function() {
      return ($('article')).each(function() {
        return handle_article($(this));
      });
    };
    main();
    return setInterval(function() {
      return main();
    }, 1000);
  });

}).call(this);
